%YAML:1.0

#common parameters
#num of map
num: 10
# path of map
map_path: "/home/gp/data/map/"

#relationship of neighbor eg:this ID,neighbor ID.
map1: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [1, 2, 3, 4]

map2: !!opencv-matrix
   rows: 2
   cols: 1
   dt: d
   data: [2, 1]

map3: !!opencv-matrix
   rows: 2
   cols: 1
   dt: d
   data: [3, 1]

map4: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [4, 1, 5]

map5: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [5, 4, 6]

map6: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [6, 5, 7]

map7: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [7, 6, 8]

map8: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [8, 7, 9, 9]

map9: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [9, 8, 8, 10]

map10: !!opencv-matrix
   rows: 2
   cols: 1
   dt: d
   data: [10, 9]




